### ISSUE TITLE
Maxpos value

### ISSUE THREAD

**Issue by Tongdongq** [libcg/bfp#19]
The library does not include easy min/maxpos values, so I made some code:

		int W = 32, es = 2;
		Posit p = Posit(W, es);
		unsigned long t = 1;
		p.setBits(t);
		p.print();
		t = 1<<(W-1);
		p.setBits(~t);
		p.print();

Output
{32, 2} 00000000000000000000000000000001 -> +0000000000000000000000000000001 = 7.52316e-37
{32, 2} 01111111111111111111111111111111 -> +1111111111111111111111111111111 = 8.50706e+37

Performing "{:.5E}".format((2*\*2)**(2*30)) in Python returns 1.32923e+36 (factor 64x lower), which is also returned as maxpos by SoftPosit (https://gitlab.com/cerlane/SoftPosit).

The same code for es=3 prints
{32, 3} 00000000000000000000000000000001 -> +0000000000000000000000000000001 = 5.6598e-73
{32, 3} 01111111111111111111111111111111 -> +1111111111111111111111111111111 = 7.23701e+75
Whereas the online references note 6e-73 to 2e72 as dynamic range for W=32,es=3, maxpos seems off again.

**Comment by libcg** [comment]
I'm not sure what you're trying to do here. What is maxpos?

**Comment by Tongdongq** [comment]
I am trying to determine the range of the posit representation. This depends on the number of bits, and the number of exponent bits. To my knowledge, the two bit patterns shown represent the minimum and maximum positive values.

**Comment by libcg** [comment]
Oh, I see. Good catch. Will investigate.

**Comment by libcg** [comment]
I identified an issue with bit shifting that was causing a wrong exponent value to be calculated. However, this issue is not entirely fixed.

**Comment by digital-codes** [comment]
I think the error comes from CLZ:
define CLZ(n) \
((n) == 0 ? POSIT_WIDTH : __builtin_clz(n))

On the max value n is 0 and this returns 32 - the Posit width. But it should return 31. Because the sign bit has to be subtracted. I have a slightly different print function (exponent left, fraction right, then Posit) which is now OK, I believe:
{32, 2} + 00000000000000000000000001111000 00000000000000000000000000000000 -> 0 1111111111111111111111111111111   : 1.32923e+36
{32, 2} + 00000000000000000000000001110100 00000000000000000000000000000000 -> 0 1111111111111111111111111111110   : 8.30767e+34
{32, 2} + 00000000000000000000000001110000 00000000000000000000000000000000 -> 0 111111111111111111111111111110 0  : 5.1923e+33
{32, 2} + 00000000000000000000000001101100 00000000000000000000000000000000 -> 0 11111111111111111111111111110 00   : 3.24519e+32
{32, 2} + 00000000000000000000000001101000 00000000000000000000000000000000 -> 0 1111111111111111111111111110 00 0  : 2.02824e+31
.....
{32, 2} + 11111111111111111111111110100000 00000000000000000000000000000000 -> 0 0000000000000000000000001 00 0000  : 1.26218e-29
{32, 2} + 11111111111111111111111110011100 00000000000000000000000000000000 -> 0 00000000000000000000000001 00 000  : 7.88861e-31
{32, 2} + 11111111111111111111111110011000 00000000000000000000000000000000 -> 0 000000000000000000000000001 00 00  : 4.93038e-32
{32, 2} + 11111111111111111111111110010100 00000000000000000000000000000000 -> 0 0000000000000000000000000001 00 0  : 3.08149e-33
{32, 2} + 11111111111111111111111110010000 00000000000000000000000000000000 -> 0 00000000000000000000000000001 00   : 1.92593e-34
{32, 2} + 11111111111111111111111110001100 00000000000000000000000000000000 -> 0 000000000000000000000000000001 0  : 1.20371e-35
{32, 2} + 11111111111111111111111110001000 00000000000000000000000000000000 -> 0 0000000000000000000000000000001   : 7.52316e-37

My clz looks like:
inline int8_t util_clz(POSIT_UTYPE p)
{
    uint8_t i;
    for (i = TSIZE; i>1; i--)
    {
        if (p & (LSHIFT(1,(i - 1))))
            break;
    }
    return TSIZE - i;
}

because I target an FPGA implementation, so builtin is not useful.

**Comment by libcg** [comment]
I think `CLZ(0) = 32` makes sense, but the shift needs to be taken into account by the caller.

**Comment by digital-codes** [comment]
sure, clz(0) = 32 ist OK normally, But you call CLZ with a prior
leftshift to get rid of the sign. I have changed many things wrt your
code but there is the same issue.

in unpack_posit you call

    int lz = CLZ(LSHIFT(p, ss));
    int lo = CLZ(LSHIFT(~p, ss));

This shifts p by one bit and you get result 32 when p is 0. This is the
problem: it should be 31.

**Comment by libcg** [comment]
OK, that makes sense. Thanks!

**Comment by libcg** [comment]
Fixed with e97b432. Thanks for the report!
