### ISSUE TITLE
Add C implementation and layer a C++ binding on top of that

### ISSUE THREAD

**Issue by libcg** [libcg/bfp#5]
Required to make it usable with embedded projects. For now it's better to keep C++ to facilitate hacking until we get something that works.

**Comment by Art** [comment]
Aloha, Hi  Clement Guerin.

I'm very interested pfp; because "... do more arithmetic **_per watt_** ...

Attended the SU EE380 presentation.

Followed up Isaac T Yonemoto julia work
[https://news.ycombinator.com/item?id=13770943](url)

Is it too early to try C / C++ to WebAssembly?
[https://github.com/WebAssembly/design/blob/master/CAndC++.md](url)

Should I add that as an "issue"?
Or ... C to Rust to ...?

Mahalo, Thanks! Art

**Comment by icepic** [comment]
Yes, that would be nice. Tried it on mac and had to add -std=c++11 in order for delayed constructors to be allowed, so if this project aims to cover a few older/more limited platforms, perhaps holding back on fancy compiler/language features is in order until it's a bit more feature complete in terms of the posit math, then look at optimizing or "modernizing" it.

**Comment by libcg** [comment]
I'm working with the latest GCC so I didn't realize I was using fancy C++ features. Any PR to fix that would be appreciated :)

C port is definitely planned because I plan to use the lib in an embedded project.

**Comment by libcg** [comment]
`posit.cpp` is very thin now and most of the logic is in other C files. Closing.
